console.log("hello K2");
var sum = 10 + 10;
console.log(sum);
var difference = 34 - 20;
console.log(difference);
var product = 10 * 8;
console.log(product);
var quotient = 10 / 5;
console.log(quotient);
var myVar = 45;
myVar++;
console.log(myVar);
var subVar = 70;
subVar--;
console.log(subVar);
var decimals = 0.5 * 2.3;
console.log(decimals);
var numFun = 5.43;
var numNum = 6.7888;
var b = numFun * numNum;
console.log(b);
var c = 56;
c = 3 + c;
c += 3;
// reads top to bottom so at first its 56 then 59 then 62
console.log(c);
var a = 45;
var b = 2;
var c = 98;
a += 5;
b += 4;
c += 2;
console.log(a,b,c);
var a = 69;
var b = 45;
var c = 399;
a -= 9;
b -= 5;
c -= 299;
console.log(a,b,c);
var a = 3;
var b = 8;
var c = 9;
a *= 3;
b *= 2;
c *= 9;
console.log(a,b,c);
var a = 81;
var b = 50;
var c = 144;
a /= 9;
b /= 5;
c /= 12;
console.log(a,b,c);
var myString = "idk";
var sillyString = "like my bff jill";
var string = myString + " " + sillyString;
console.log(string);
var sheSaid = "She said \"Hi how are you?\"";
console.log(sheSaid);